// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWkz-lgIAB7mCd87h05wLnFt3Nw3G_xuA',
    appId: '1:276641194795:web:f74176044d5d0f313c9b6e',
    messagingSenderId: '276641194795',
    projectId: 'bilalapp-c6b7f',
    authDomain: 'bilalapp-c6b7f.firebaseapp.com',
    storageBucket: 'bilalapp-c6b7f.firebasestorage.app',
    measurementId: 'G-X54MNGR0TT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy0PLQfKFo7Qsbj_D3qDDO2OaROgo62kc',
    appId: '1:276641194795:android:ff74d479ab0b78f93c9b6e',
    messagingSenderId: '276641194795',
    projectId: 'bilalapp-c6b7f',
    storageBucket: 'bilalapp-c6b7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU31lLYYYu7XC8eEYQfVp_4qsMqPORrbk',
    appId: '1:276641194795:ios:29446e0673a9de7e3c9b6e',
    messagingSenderId: '276641194795',
    projectId: 'bilalapp-c6b7f',
    storageBucket: 'bilalapp-c6b7f.firebasestorage.app',
    iosBundleId: 'com.bilal.bilalApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU31lLYYYu7XC8eEYQfVp_4qsMqPORrbk',
    appId: '1:276641194795:ios:29446e0673a9de7e3c9b6e',
    messagingSenderId: '276641194795',
    projectId: 'bilalapp-c6b7f',
    storageBucket: 'bilalapp-c6b7f.firebasestorage.app',
    iosBundleId: 'com.bilal.bilalApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWkz-lgIAB7mCd87h05wLnFt3Nw3G_xuA',
    appId: '1:276641194795:web:f82813c20487520e3c9b6e',
    messagingSenderId: '276641194795',
    projectId: 'bilalapp-c6b7f',
    authDomain: 'bilalapp-c6b7f.firebaseapp.com',
    storageBucket: 'bilalapp-c6b7f.firebasestorage.app',
    measurementId: 'G-GQTWT95YVJ',
  );
}
